# Copyright 2025 Stoolap Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Any, Optional, Union, Dict, List, Sequence

Params = Optional[Union[List[Any], tuple, Dict[str, Any]]]
ParamSet = Union[List[Any], tuple]

__all__: list[str]

class StoolapError(RuntimeError): ...

class Database:
    @staticmethod
    def open(path: str = ":memory:") -> "Database": ...
    def execute(self, sql: str, params: Params = None) -> int: ...
    def exec(self, sql: str) -> None: ...
    def query(self, sql: str, params: Params = None) -> List[Dict[str, Any]]: ...
    def query_one(self, sql: str, params: Params = None) -> Optional[Dict[str, Any]]: ...
    def query_raw(self, sql: str, params: Params = None) -> Dict[str, Any]: ...
    def execute_batch(self, sql: str, params_list: Sequence[ParamSet]) -> int: ...
    def prepare(self, sql: str) -> "PreparedStatement": ...
    def begin(self) -> "Transaction": ...
    def close(self) -> None: ...

class Transaction:
    def execute(self, sql: str, params: Params = None) -> int: ...
    def query(self, sql: str, params: Params = None) -> List[Dict[str, Any]]: ...
    def query_one(self, sql: str, params: Params = None) -> Optional[Dict[str, Any]]: ...
    def query_raw(self, sql: str, params: Params = None) -> Dict[str, Any]: ...
    def execute_batch(self, sql: str, params_list: Sequence[ParamSet]) -> int: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> "Transaction": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class PreparedStatement:
    @property
    def sql(self) -> str: ...
    def execute(self, params: Params = None) -> int: ...
    def query(self, params: Params = None) -> List[Dict[str, Any]]: ...
    def query_one(self, params: Params = None) -> Optional[Dict[str, Any]]: ...
    def query_raw(self, params: Params = None) -> Dict[str, Any]: ...
    def execute_batch(self, params_list: Sequence[ParamSet]) -> int: ...

class AsyncDatabase:
    @classmethod
    async def open(cls, path: str = ":memory:") -> "AsyncDatabase": ...
    async def execute(self, sql: str, params: Params = None) -> int: ...
    async def exec(self, sql: str) -> None: ...
    async def query(self, sql: str, params: Params = None) -> List[Dict[str, Any]]: ...
    async def query_one(self, sql: str, params: Params = None) -> Optional[Dict[str, Any]]: ...
    async def query_raw(self, sql: str, params: Params = None) -> Dict[str, Any]: ...
    async def execute_batch(self, sql: str, params_list: Sequence[ParamSet]) -> int: ...
    def prepare(self, sql: str) -> "AsyncPreparedStatement": ...
    async def begin(self) -> "AsyncTransaction": ...
    async def close(self) -> None: ...

class AsyncTransaction:
    async def execute(self, sql: str, params: Params = None) -> int: ...
    async def query(self, sql: str, params: Params = None) -> List[Dict[str, Any]]: ...
    async def query_one(self, sql: str, params: Params = None) -> Optional[Dict[str, Any]]: ...
    async def query_raw(self, sql: str, params: Params = None) -> Dict[str, Any]: ...
    async def execute_batch(self, sql: str, params_list: Sequence[ParamSet]) -> int: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def __aenter__(self) -> "AsyncTransaction": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class AsyncPreparedStatement:
    @property
    def sql(self) -> str: ...
    async def execute(self, params: Params = None) -> int: ...
    async def query(self, params: Params = None) -> List[Dict[str, Any]]: ...
    async def query_one(self, params: Params = None) -> Optional[Dict[str, Any]]: ...
    async def query_raw(self, params: Params = None) -> Dict[str, Any]: ...
    async def execute_batch(self, params_list: Sequence[ParamSet]) -> int: ...
